### ISSUE TITLE
req.headers['x-auth'] is empty

### ISSUE THREAD

**Issue by zhouhao27** [eljamaki01/NewsWatcher2RWeb#1]
When I tried to delete user id from User.js or in Session.js, the req.headers['x-auth'] is always empty. But I've logged in through Session post API already which returned the userId and Token etc. So I should add something in req.headers['x-auth'] by myself? Thanks.

**Comment by eljamaki01** [comment]
If you look at the test code for the API you can see how the x-auth header is used. Look in the file functional_api_crud.js. The tests are from the client code point of view for usage with the backend API. So the test code does a log in and then the session path returns the token that is then used as the authentication for the rest of the calls using that token as the x-auth. The id for usage with MongoDB needs to be kept if you want to know who the logged in user is so you can retrieve their documents. If you are changing the code for you own reasons and don’t need the user id then you don’t need that. That id is the key assigned by MongoDB though and very important.

**Comment by zhouhao27** [comment]
Sorry, I misunderstand. Thanks for your reply.
