### ISSUE TITLE
Build folder missing

### ISSUE THREAD

**Issue by gminova** [eljamaki01/NewsWatcher2RWeb#3]
I'm if I'm being silly but the react build folder is missing. How can I start the project? The documentation is not very clear. Thank you

**Comment by eljamaki01** [comment]
You need to build the React app project first. To do that, you go to the directory of the project and run "react-scripts build" The build directory will then appear. Then if you have the node application serving it you can run the node server and connect in the browser and see it. You can also just run the React also by running "react-scripts build".

**Comment by eljamaki01** [comment]
You can see from the React web site itself that you can use create-react-app and then follow the same simple step to be up and running. https://reactjs.org/docs/create-a-new-react-app.html
