### ISSUE TITLE
Sample Document Json

### ISSUE THREAD

**Issue by williamgosse** [eljamaki01/NewsWatcher2RWeb#4]
Can you post the json for the sample documents referenced in the book.  Thanks in advance.

**Comment by eljamaki01** [comment]
// Customer Documents
{
	"_id": "77",
	"type": "CUSTOMER_TYPE",
	"name": "Joe Schmoe",
	"age": 27,
	"email": "js@gmail.com",
	"address": {
		"street": "21 Main Street",
		"city": "Emerald City",
		"state": "KS",
		"postalCode": "10021-3100"
	},
	"rewardsPoints": 99,
	"booksPurchased": [
		{
			"id": "1098",
			"title": "Agile Project Management with Kanban"
		},
		{
			"id": "1099",
			"title": "The Merriam-Webster Dictionary"
		}
	]
},{
	"_id": "78",
	"type": "CUSTOMER_TYPE",
	"name": "Jane Doe",
	"age": 37,
	"email": "jd@gmail.com",
	"address": {
		"street": "100 S Bridger Blvd",
		"city": "Paradise",
		"state": "UT",
		"postalCode": "84328"
	},
	"rewardsPoints": 0
}

// Book Documents
{
	"_id": "1098",
	"type": "BOOK_TYPE",
	"title": "Agile Project Management with Kanban",
	"ISBN10": "0735698953",
	"author": "Eric Brechner",
	"pages": 160,
	"format": "Paperback",
	"price": 27.66,
	"publicationDate": "20150326",
	"category": "Software Engineering",
	"bookReviews": [
		{
			"reviewer": "Joe Schmoe",
			"date": "20140321",
			"comments": "Wish I had this years ago!",
			"rating": 4
		},{
			"reviewer": "Jane Doe",
			"date": "20150923",
			"comments": "Forever a classic.",
			"rating": 5
		}]
},{
	"_id": "1099",
	"type": "BOOK_TYPE",
	"title": "The Merriam-Webster Dictionary",
	"ISBN10": "087779930X",
	"author": "Merriam-Webster",
	"pages": 939,
	"format": "Paperback",
	"price": 11.26,
	"publicationDate": "20040701",
	"category": "English",
	"bookReviews": [
		{
			"reviewer": "Joe Schmoe",
			"date": "20100101",
			"comments": "A terrific volume to keep handy.",
			"rating": 4
		},{
			"reviewer": "Jane Doe",
			"date": "20120817",
			"comments": "Wish it came in an audio book format.",
			"rating": 2
		}]
}
